return {
    fileencoding   = "utf-8",
    termencoding   = "utf-8",
    encoding       = "utf-8",
    tabstop        = 4,
    shiftwidth     = 4,
    softtabstop    = 4,
    expandtab      = true,
    smarttab       = true,
    incsearch      = true,
    autoindent     = true,
    smartindent    = true,
    number         = true,
    relativenumber = true,
    cursorline     = true,
    termguicolors  = true,
    ignorecase     = true,
    wrap           = false,
    wildmenu       = true,
    wildmode       = "list:longest,full",
    wildignore     = "*.o,*.pyc",
    backspace      = "indent,eol,start",
    foldenable     = true,
    mouse          = "a",
    hlsearch       = false,

    ["g"] = {
        mapleader = " ",
    },

}
